################################################################
# Makefile.in : compiling options for the 		       #
# Makefile for GADGET and AHF related reading routines,        #
# growth factor calculations, integrations and interpolations  #
################################################################

# Convert units from kpc to Mpc
OPT    += -DUSE_UNIT_MPC
# Print additional informations
OPT	+= -DPRINT_INFO
OPT	+= -DPRINT_HALO
# Catalogue - reading options
OPT	+= -DGAS
OPT	+= -DSKIP_SOFT
OPT	+= -DEXTRA_GAS
# Don't use nor search data from the simulations
#OPT	+= -DTH_ONLY
# Use a subset of haloes only when computing axis alignment
OPT	+= -DUSE_SAMPLE

# Enable MPI version
WITH_MPI="on"
WITH_OMP="on"

NUM_OMP_THREADS=8

# Choose your system
#SYS="laptop"
SYS="comodo"
#SYS="castor"
#SYS="casa"
#SYS="popia"

CC      = /usr/bin/gcc
CFLAGS  =

ifeq (${SYS}, "laptop")
CFLAGS  += -lgsl -lgslcblas -lm -lrt
CFLAGS  += -Wall ${CLIBS}
INCLUDE  = -I/usr/include ${CINCL}
BASELIBS = -L/usr/lib 
HOME_DIR = /home/edoardo/Analysis/
endif

ifeq (${SYS}, "castor")
ADD_LIB = "on"
CFLAGS  += -lgsl -lgslcblas -lm
INCLUDE =
HOME_DIR=/home/carlesi/Analysis/
endif

ifeq (${SYS}, "casa")
ADD_LIB = "on"
CFLAGS  += -lgsl -lgslcblas -lm
INCLUDE =
HOME_DIR=/home/edoardo/Analysis/
endif

ifeq (${SYS}, "comodo")
HOME_DIR=/home/edoardo/Analysis/
CFLAGS  += -lgsl -lgslcblas -lm
CFLAGS  += -L/home/edoardo/libs/lib
INCLUDE = -I/usr/local/include 
INCLUDE += -I/home/edoardo/libs/include
BASELIBS += -L/home/carlesi/libs/lib
HOME_DIR = /home/edoardo/Analysis/
endif

ifeq (${WITH_MPI}, "on")
CC = mpicc
OPT += -DWITH_MPI
endif

ifeq (${WITH_OMP}, "on")
OPT += -DOMP_THREADS=${NUM_OMP_THREADS}
CFLAGS	+= -fopenmp
endif
